project:
  type: website

website:
  title: "Walasse Tomaz"
  favicon: "favicon.png"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Walassseee
format:
  html:
    theme: default
    css: styles.css



